Working on the backdrop animation, but there is a typing issue which I don't understand... :(

diff --git a/tool/push_web b/tool/push_web
--- a/tool/push_web
+++ b/tool/push_web
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Exit on error
+set -e
+
 # Script for pushing a built web app to my website repo
 if [ "${PWD##*/}" != 'portfolio_web' ]; then
     echo 'Called from wrong directory!'
